language: php
php:
- 7.4

services:
- mysql

before_script:
- composer install
- mysql -e 'create database linna_db;'
- mysql -u root linna_db < vendor/linna/db-dumps/src/linna_db_mysql_test.sql

script:
- ./vendor/bin/phpunit
